version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitActionsTempProject
  gitServerName: poanTestGit
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testgitactionstemp.integrations:createdFlow
  packages:
  - name: TestGitActionsTempProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1999
